const BASE_URL = "http://192.168.223.54:8000/";
const COMPLETED = "COMPLETED";
const REPORTED = "REPORTED";
const REJECTED = "REJECTED";
const CANCELLED = "CANCELLED";
const PENDING = "PENDING"
const ACCEPTED = "ACCEPTED"
const   IN_PROGRESS = "IN PROGRESS"
export { BASE_URL, COMPLETED, REPORTED, CANCELLED, ACCEPTED, PENDING, IN_PROGRESS, REJECTED};
